language: go

sudo: required
dist: trusty

go:
- "1.9"
- "1.10"
- "1.11"

before_install: true

install: true

before_script:
- cd "${TRAVIS_BUILD_DIR}"

script:
- make -f Makefile dep
- go test -race -coverprofile=coverage.txt -covermode=atomic ./...

branches:
  only:
  - master

notifications:
  email:
    on_success: never
    on_failure: change

after_success:
  - bash <(curl -s https://codecov.io/bash)